doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            vacancy_id: 'App\Model\Vacancy\Entity\IdType'
            vacancy_status: 'App\Model\Vacancy\Entity\StatusType'
            person_id: 'App\Model\Person\Entity\Person\IdType'
            person_email: 'App\Model\Person\Entity\Person\EmailType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Vacancy/Entity'
                prefix: 'App\Model\Vacancy\Entity'
                alias: Vacancy
            Person:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Person/Entity'
                prefix: 'App\Model\Person\Entity'
                alias: Person
